
name: Cross-compile the SD image for a Raspberry Pi 5

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
  workflow_dispatch:

jobs:
  cross-compile-geniux:
    runs-on: self-hosted
 
    steps:
      - name: Cross-compile gnss-sdr-dev-image for the raspberrypi 5
        shell: bash
        run: |
          mkdir -p ~/oe-repo
          cd ~/oe-repo
          git config --global color.ui false
          repo init -v -u https://github.com/carlesfernandez/oe-gnss-sdr-manifest.git -b scarthgap
          repo sync
          TEMPLATECONF=$(pwd)/meta-gnss-sdr/conf/templates/default source ./oe-core/oe-init-build-env ./build ./bitbake
          MACHINE=raspberrypi5 bitbake gnss-sdr-dev-image

