name: Cross-compile GNSS-SDR for a Raspberry Pi 5

on:
  # Run after the cross-compilation of the GNSS-SDR is finished
  workflow_run:
    workflows: ["Cross-compile the SD image for a Raspberry Pi 5"] 
    types:
      - completed  
    
  workflow_dispatch:
     

jobs:
  cross-compile-gnss-sdr:
    runs-on: self-hosted
    steps:
      - name: Clone gnss-sdr
        uses: actions/checkout@v4
        with:
          repository: 'gnss-sdr/gnss-sdr'
          path: gnss-sdr
          ref: next
          submodules: recursive
          fetch-depth: 0
          
      - name: Cross-compile gnss-sdr for the raspberrypi 5
        run: |
          env
          unset LD_LIBRARY_PATH
          . ~/raspberrypi-sdk/environment-setup-cortexa76-geniux-linux
          env|grep -e "^LD" -e "^CC" -e "^AR"
          cd gnss-sdr

          max_retries=5
          retry_delay=1
          
          rm -rf build/ || true
          
          for attempt in $(seq 1 "$max_retries"); do
              echo "Attempt $attempt of $max_retries..."
              
              if  cmake -S . -B build -DCMAKE_TOOLCHAIN_FILE=cmake/Toolchains/oe-sdk_cross.cmake -DCMAKE_INSTALL_PREFIX=/usr -DENABLE_SYSTEM_TESTING=ON -DENABLE_SYSTEM_TESTING_EXTRA=ON; then
                  echo "Cmake configure succeeded on attempt $attempt."
                  break  # Exit the loop on success
              else
                  echo "Command failed on attempt $attempt."
                  if [ "$attempt" -lt "$max_retries" ]; then
                      echo "Retrying in $retry_delay seconds..."
                      sleep "$retry_delay"
                  else
                      echo "cmake configure failed after $max_retries attempts."
                      exit 1  # Exit the script with an error if all retries fail
                  fi
              fi
          done
         
          cmake --build build/ -j
          sshfs root@10.1.3.134:/ /mnt/sdimage2
          cmake --install build/ --prefix /mnt/sdimage2/
          rsync -av build/tests/ /mnt/sdimage2/home/root/gnss-sdr-tests
          umount /mnt/sdimage2
