name: Cross-compile GNSS-SDR for a Raspberry Pi 5

on:
  workflow_dispatch:

jobs:
  cross-compile-gnss-sdr:
    runs-on: self-hosted
    steps:
      - name: Clone gnss-sdr
        uses: actions/checkout@v4
        with:
          repository: 'gnss-sdr/gnss-sdr'
          path: gnss-sdr
          ref: next
          submodules: recursive
          fetch-depth: 0
          
      - name: Cross-compile gnss-sdr for the raspberrypi 5
        run: |
          env
          unset LD_LIBRARY_PATH
          . ~/raspberrypi-sdk/environment-setup-cortexa76-geniux-linux
          env|grep -e "^LD" -e "^CC" -e "^AR"
          cd gnss-sdr
          cmake -S . -B build -DCMAKE_TOOLCHAIN_FILE=cmake/Toolchains/oe-sdk_cross.cmake -DCMAKE_INSTALL_PREFIX=/usr -DENABLE_SYSTEM_TESTING=ON
          cmake --build build -j
          sshfs root@10.1.3.134:/ /mnt/sdimage2
          cmake --install build/ --prefix /mnt/sdimage2/
          umount /mnt/sdimage2
