name: Test GNSS-SDR in a Raspberry Pi 5

on:
  # Run after the deployment of the GNSS-SDR is finished
  workflow_run:
    workflows: ["Deploy the image and GNSS-SDR in a Raspberry Pi 5"] 
    types:
      - completed  

  workflow_dispatch:

jobs:
  cross-compile-gnss-sdr:
    runs-on: self-hosted
    steps:         
      - name: Clone gnss-sdr
        uses: actions/checkout@v4
        with:
          repository: 'gnss-sdr/gnss-sdr'
          path: gnss-sdr
          ref: next
          
      - name: Test gnss-sdr in the Raspberrypi 5
        run: |
            ssh root@10.1.3.134 gnss-sdr-tests/run_tests --gtest_color=no --gtest_output=xml --gtest_filter="ReedSolomonE1BTest*"
            rsync -av root@10.1.3.134:/home/root/test_detail.xml /home/xavier/actions-runner/_work/gnss-sdr/gnss-sdr/gnss-sdr/
       
      - name: Upload JUnit Results
        uses: phoenix-actions/test-reporting@v8
        id: test-report               # Set ID reference for step
        if: always()
        with:
          name: JUnit Tests
          path: test_detail.xml
          reporter: java-junit
          working-directory: /home/xavier/actions-runner/_work/gnss-sdr/gnss-sdr/gnss-sdr/
      
      #      echo "$errors" | jq -r '.[] | "Test: \(.test), Message: \(.message)"'
      #    fi

