name: Test GNSS-SDR in a Raspberry Pi 5

on:
  # Run after the deployment of the GNSS-SDR is finished
  workflow_run:
    workflows: ["Deploy the image and GNSS-SDR in a Raspberry Pi 5"] 
    types:
      - completed  

  workflow_dispatch:

jobs:
  test-gnss-sdr:
    runs-on: self-hosted
    steps:                  
      - name: Load test report history
        uses: actions/checkout@v4
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Test gnss-sdr in the Raspberrypi 5
        run: |
            ssh -o "StrictHostKeyChecking=no" -o "UserKnownHostsFile=/dev/null" root@10.1.3.134 "./separated-tests.bash || true"
            rsync -av root@10.1.3.134:/home/root/test-results/* allure-results/
            ssh -o "StrictHostKeyChecking=no" -o "UserKnownHostsFile=/dev/null" root@10.1.3.134 "rm -v test-results/* || true"

      - name: Build test report
        uses: simple-elf/allure-report-action@v1.10
        if: always()
        with:
          gh_pages: gh-pages
          allure_results: allure-results
          allure_report: allure-report
          allure_history: allure-history

      - name: Publish test report
        uses: peaceiris/actions-gh-pages@v4
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history      

