name: Test GNSS-SDR in a Raspberry Pi 5

on:
  # Run after the deployment of the GNSS-SDR is finished
  workflow_run:
    workflows: ["Deploy the image and GNSS-SDR in a Raspberry Pi 5"] 
    types:
      - completed  

  workflow_dispatch:

jobs:
  test-gnss-sdr:
    runs-on: self-hosted
    steps:         
      - name: Clone gnss-sdr
        uses: actions/checkout@v4
        with:
          repository: 'gnss-sdr/gnss-sdr'
          path: gnss-sdr
          ref: next
          
      - name: Test gnss-sdr in the Raspberrypi 5
        run: |
            ssh -o "StrictHostKeyChecking=no" -o "UserKnownHostsFile=/dev/null" root@10.1.3.134 gnss-sdr-tests/run_tests --gtest_color=no --gtest_output=xml --gtest_filter="ReedSolomonE1BTest*"
            rsync -av root@10.1.3.134:/home/root/test_detail.xml /home/xavier/actions-runner/_work/gnss-sdr/gnss-sdr/gnss-sdr/
       
      #- name: Upload JUnit Results
      #  uses: phoenix-actions/test-reporting@v8
      #  id: test-report             
      #  if: always()
      #  with:
      #    name: JUnit Tests
      #    path: test_detail.xml
      #    reporter: java-junit
      #    working-directory: /home/xavier/actions-runner/_work/gnss-sdr/gnss-sdr/gnss-sdr/

      - name: Load test report history
        uses: actions/checkout@v4
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Build test report
        uses: simple-elf/allure-report-action@v1.10
        if: always()
        with:
          gh_pages: gh-pages
          allure_results: /home/xavier/actions-runner/_work/gnss-sdr/gnss-sdr/gnss-sdr/
          allure_report: allure-report
          allure_history: allure-history

      - name: Publish test report
        uses: peaceiris/actions-gh-pages@v4
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history      

