name: Test TTFF GNSS-SDR in a Raspberry Pi 5

on:
  # Run every day at midnight
  schedule:
    - cron: '0 0 * * *'

  workflow_dispatch:

jobs:
  ttff-gnss-sdr:
    runs-on: self-hosted
    steps:                  
      - name: Load test report history
        uses: actions/checkout@v4
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Test TTFF gnss-sdr in the Raspberrypi 5
        run: |
            ssh -o "StrictHostKeyChecking=no" -o "UserKnownHostsFile=/dev/null" root@10.1.3.134 "gnss-sdr-tests/ttff --num_measurements 800 --config_file_ttff gnss-sdr-tests/test-osmo.conf --gtest_color=no --gtest_output=xml:test-results/ || true"
            rsync -av root@10.1.3.134:/home/root/test-results/* allure-results/

      - name: Build test report
        uses: simple-elf/allure-report-action@v1.10
        if: always()
        with:
          gh_pages: gh-pages
          allure_results: allure-results
          allure_report: allure-report
          allure_history: allure-history

      - name: Publish test report
        uses: peaceiris/actions-gh-pages@v4
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history      

      - name: Delete test files
        if: always()
        run: |
           echo 
            #rm -v "/tmp/allure-results/*" || true
            #ssh -o "StrictHostKeyChecking=no" -o "UserKnownHostsFile=/dev/null" root@10.1.3.134 "rm -v test-results/* || true"
